apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
        app.kubernetes.io/component: gateways
        app.kubernetes.io/instance: ci00058876-idevgen1ds-control-panel
        app.kubernetes.io/managed-by: maistra-istio-operator
        app.kubernetes.io/name: gateways
        app.kubernetes.io/part-of: istio
        app.kubernetes.io/version: 1.0.2-7.el8-1
        chart: gateways
        heritage: Tiller
        istio: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
        maistra.io/owner: ci00058876-idevgen1ds-control-panel
        release: istio
      name: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
    spec:
      progressDeadlineSeconds: 1200
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
          istio: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
        type: RollingUpdate
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          creationTimestamp: null
          labels:
            app: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
            chart: gateways
            heritage: Tiller
            istio: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
            release: istio
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - amd64
                weight: 2
              - preference:
                  matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - ppc64le
                weight: 2
              - preference:
                  matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - s390x
                weight: 2
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - amd64
                    - ppc64le
                    - s390x
          containers:
          - args:
            - proxy
            - router
            - --domain
            - $(POD_NAMESPACE).svc.cluster.local
            - --log_output_level=default:info
            - --drainDuration
            - 45s
            - --parentShutdownDuration
            - 1m0s
            - --connectTimeout
            - 10s
            - --serviceCluster
            - ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
            - --zipkinAddress
            - zipkin.ci00058876-idevgen1ds-control-panel:9411
            - --proxyAdminPort
            - "15000"
            - --statusPort
            - "15020"
            - --controlPlaneAuthPolicy
            - NONE
            - --discoveryAddress
            - istio-pilot.ci00058876-idevgen1ds-control-panel:15010
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: ISTIO_META_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: ISTIO_META_CONFIG_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
            image: registry.ca.sbrf.ru/ci01563053/ocp4/operatorhub/openshift-service-mesh/proxyv2-rhel8@sha256:2c2b61347776708a7e46f9bea54384e941f1ed6d4cd5a21e50eaf3cbf770d4f2
            imagePullPolicy: IfNotPresent
            name: istio-proxy
            ports:
            - containerPort: 15020
              name: status-port
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 5443
              name: https
              protocol: TCP
            readinessProbe:
              failureThreshold: 30
              httpGet:
                path: /healthz/ready
                port: 15020
                scheme: HTTP
              initialDelaySeconds: 1
              periodSeconds: 2
              successThreshold: 1
              timeoutSeconds: 5
            resources:
              limits:
                cpu: 600m
                memory: 900Mi
              requests:
                cpu: 400m
                memory: 700Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/istio/proxy
              name: istio-envoy
  #          - mountPath: /etc/certs/
  #            name: istio-certs
  #            readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 60
          volumes:
          - emptyDir:
              medium: Memory
            name: istio-envoy
  #        - name: istio-certs
  #          secret:
  #            defaultMode: 400
  #            optional: true
  #            secretName: istio.default
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
        istio: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
      name: ingressgateway-svc
    spec:
      ports:
      - name: status-port
        port: 15020
        protocol: TCP
        targetPort: 15020
      - name: http-8080
        port: 8080
      selector:
        app: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
        istio: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
  - apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: ingressgateway-gw
    spec:
      selector:
        istio: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
      servers:
      - hosts:
        - ingress-ci00058876.apps.sh1.dev-gen1-ds.ca.sbrf.ru
        port:
          name: http-8080
          number: 8080
          protocol: HTTP

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
        istio: ingressgateway-ci00058876-idevgen1ds-way-stream-openshift-1
      name: ingressgateway-http
    spec:
      host: ingress-ci00058876.apps.sh1.dev-gen1-ds.ca.sbrf.ru
      port:
        targetPort: http-8080
      to:
        kind: Service
        name: ingressgateway-svc

  - apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: internal-host-vs
    spec:
      exportTo:
      - .
      gateways:
      - ingressgateway-gw
      hosts:
      - ingress-ci00058876.apps.sh1.dev-gen1-ds.ca.sbrf.ru
      http:
      - match:
        - uri:
            prefix: /*
        route:
        - destination:
            host: app-for-test-connect-svc-a
            port:
              number: 8080