apiVersion: v1
kind: Template
labels:
  app: ${APP_NAME}
  template: ${APP_NAME}
message: ${APP_NAME}
metadata:
  annotations:
    description: ${APP_NAME}.
    openshift.io/display-name: ${APP_NAME}
    version: 1.0.0
  name: egress
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: egressgateway${EXTERNAL_HOST_NUMBER}-svc
  spec:
    ports:
    - name: tcp-${EGRESS_PORT}
      port: ${{EGRESS_PORT}}
    selector:
      app: egressgateway-${PROJECT_NAME}
      istio: egressgateway-${PROJECT_NAME}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: egressgateway-${PROJECT_NAME}
      app.kubernetes.io/component: gateways
      app.kubernetes.io/instance: ${ISTIO_CONTROL_PLANE}
      app.kubernetes.io/managed-by: maistra-istio-operator
      app.kubernetes.io/name: gateways
      app.kubernetes.io/part-of: istio
      app.kubernetes.io/version: 1.0.2-7.el8-1
      chart: gateways
      heritage: Tiller
      istio: egressgateway-${PROJECT_NAME}
      maistra.io/owner: ${ISTIO_CONTROL_PLANE}
      release: istio
    name: egressgateway-${PROJECT_NAME}
  spec:
    progressDeadlineSeconds: 1200
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: egressgateway-${PROJECT_NAME}
        istio: egressgateway-${PROJECT_NAME}
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
        creationTimestamp: null
        labels:
          app: egressgateway-${PROJECT_NAME}
          chart: gateways
          heritage: Tiller
          istio: egressgateway-${PROJECT_NAME}
          release: istio
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
              weight: 2
            - preference:
                matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                  - ppc64le
              weight: 2
            - preference:
                matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                  - s390x
              weight: 2
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                  - ppc64le
                  - s390x
        containers:
        - args:
          - proxy
          - router
          - --domain
          - $(POD_NAMESPACE).svc.cluster.local
          - --log_output_level=default:info
          - --drainDuration
          - 45s
          - --parentShutdownDuration
          - 1m0s
          - --connectTimeout
          - 10s
          - --serviceCluster
          - egressgateway-${PROJECT_NAME}
          - --zipkinAddress
          - zipkin.${ISTIO_CONTROL_PLANE}:9411
          - --proxyAdminPort
          - "15000"
          - --statusPort
          - "15020"
          - --controlPlaneAuthPolicy
          - NONE
          - --discoveryAddress
          - istio-pilot.${ISTIO_CONTROL_PLANE}:15010
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: ISTIO_META_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: ISTIO_META_CONFIG_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: ISTIO_META_ROUTER_MODE
            value: sni-dnat
          image: ${PROXY_IMAGE}
          imagePullPolicy: IfNotPresent
          name: istio-proxy
          ports:
          - containerPort: 15020
            name: status-port
          - containerPort: 8080
            name: http
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15020
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 600m
              memory: 900Mi
            requests:
              cpu: 400m
              memory: 700Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/istio/proxy
            name: istio-envoy
          - mountPath: /etc/certs/
            name: istio-certs
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 60
        volumes:
        - emptyDir:
            medium: Memory
          name: istio-envoy
        - name: istio-certs
          secret:
            defaultMode: 400
            optional: true
            secretName: istio.default
- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: egressgateway${EXTERNAL_HOST_NUMBER}-gw
  spec:
    selector:
      istio: egressgateway-${PROJECT_NAME}
    servers:
    - hosts:
      - ${EXTERNAL_HOST}
      port:
        name: tcp-${EGRESS_PORT}
        number: ${{EGRESS_PORT}}
        protocol: TCP
- apiVersion: networking.istio.io/v1alpha3
  kind: ServiceEntry
  metadata:
    name: external-host${EXTERNAL_HOST_NUMBER}-se
  spec:
    exportTo:
    - .
    hosts:
    - ${EXTERNAL_HOST}
    ports:
    - name: tcp-${EXTERNAL_PORT}
      number: ${{EXTERNAL_PORT}}
      protocol: TCP
    resolution: DNS
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: external-host${EXTERNAL_HOST_NUMBER}-vs
  spec:
    exportTo:
    - .
    gateways:
    - egressgateway${EXTERNAL_HOST_NUMBER}-gw
    - mesh
    hosts:
    - ${EXTERNAL_HOST}
    tcp:
    - match:
      - gateways:
        - mesh
        port: ${{EXTERNAL_PORT}}
      route:
      - destination:
          host: egressgateway${EXTERNAL_HOST_NUMBER}-svc
          port:
            number: ${{EGRESS_PORT}}
    - match:
      - gateways:
        - egressgateway${EXTERNAL_HOST_NUMBER}-gw
        port: ${{EGRESS_PORT}}
      route:
      - destination:
          host: ${EXTERNAL_HOST}
          port:
            number: ${{EXTERNAL_PORT}}
parameters:
- name: PROJECT_NAME
  required: true
- name: APP_NAME
  required: true
- name: ISTIO_CONTROL_PLANE
  required: true
- name: PROXY_IMAGE
  required: true
- name: EXTERNAL_HOST
  required: true
- name: EXTERNAL_PORT
  required: true
- name: EGRESS_PORT
  required: true
- name: EXTERNAL_HOST_NUMBER
  value: null
